Add functionality for camera trap video classification
Appsilon/wildlife-explorer pull request #117
Opened 2020-07-30 01:21 UTC by rcwhytock

Apologies this might have been better as a feature request but I've made a lot of progress so it might be relatively easy to integrate. The motivation for creating it is that two large projects/organisations are very interested in the app but all of their data are in video format. Also, many organisations are keen to use video for various reasons, so video support will greatly expand the number of users who are likely to use the app.

Having thought about this a lot, the simplest way to allow users to classify videos is have them choose the folder/s with the videos and the app then automatically extracts images from the video clips and save* the images in a new directory (with the same original directory structure to preserver camera station information etc). The user can then select the new image directory and the classifier can be run in the usual way.

The PR has two python scripts:

1.functions_video.py provides functions that extract paths from a folder of video files (avi, mp4) and then re-creates the video folder's directory structure.

2. extract_frames.py is a working demo script (just provide an input video directory and an empty directory for the extracted images). The script extracts image frames from all of the videos (5 s intervals) into the new image directory with appropriate filenames and the correct directory structure. Once this is completed the user can classify the image folder as normal.

This would be a major boost to functionality. Here is a link to one of the projects that are interested, they have been trying to analyse this data for years: https://www.zooniverse.org/projects/sassydumbledore/chimp-and-see/classify

2020-08-28 11:23 UTC, marekrogala commented
@rcwhytock sounds great! thanks!

What (if any) changes from us do you see are needed to make this work?

2020-08-30 16:29 UTC, rcwhytock commented
@marekrogala I think all we need to make it work is an interface for the user to select the source directory for the video files (i.e. set the video_data_folder variable in extract_frames.py) and choose the output directory for the new images (i.e. set the new_image_data_folder variable in extract_frames.py). I've tested this on Ubuntu only and don't have access to a Windows machine right now, but I did make some effort to make it (hopefully) OS independent (but needs testing of course). 

The option to do this step could be in the classifier tab of the Mbaza app? Something like a question "Would you like to classify images or videos"? If answer equals "images" move forward to classification, if "videos" bring up the option to create the image directory from the video files, then move to classification. Does that make sense?

2020-09-08 08:22 UTC, kamilzyla requested changes
Thank you Robbie for this PR, great job! I'm adding some comments for Jędrzej who will be working on this script so it can be integrated with the app.

* Please move the translations into a separate PR.
* The two Python files are rather short; I suggest merging them into a single script.
* Please ensure that the script works correctly if the user chooses the same input and output directories.

2020-09-08 08:22 UTC, kamilzyla commented on models/runner/extract_frames.py
> +        name = os.path.dirname(os.path.abspath(videos.replace(video_data_folder, new_image_data_folder))) + '/' + get_filename(videos) + '_' + f"{frameIndex+1:02d}" + '.jpg'
Please use `os.path.relpath` and `os.path.join` instead of `str.replace` and string concatenation.

2020-09-08 08:22 UTC, kamilzyla commented on models/runner/functions_video.py
> +    return filename.endswith(("avi", ".mp4", "AVI", "MP4"))
Maybe `.lower().endswith(('avi', '.mp4'))`?

2020-09-08 08:28 UTC, marekrogala commented
> Please move the translations into a separate PR.
@kamilzyla @swiezew looks like this PR includes commits from the translations PR that I've already merged. Rebasing or merging with master should clear them up

2020-09-08 12:31 UTC, closed without merging

2020-09-08 12:33 UTC, swiezew commented
Closing this PR - processing videos will be added in [this branch](https://github.com/Appsilon/wildlife-explorer/tree/process_videos) of the main repo (code based on the scripts added here).